const avatarDesign = {
  eyes: ["open", "sleep", "wink", "glasses", "happy", "sunglasses"],
  hair: [
    "long",
    "sideShave",
    "shortCombover",
    "curlyHighTop",
    "bobCut",
    "curly",
    "pigtails",
    "curlyBun",
    "buzzcut",
    "bobBangs",
    "bald",
    "balding",
    "cap",
    "bunUndercut",
    "fade",
    "beanie",
    "straightBun",
    "extraLong",
    "shortComboverChops",
    "mohawk",
  ],
  body: ["squared", "rounded", "small", "checkered"],
  mouth: [
    "smile",
    "frown",
    "surprise",
    "pacifier",
    "bigSmile",
    "smirk",
    "lips",
  ],
  nose: ["mediumRound", "smallRound", "wrinkles"],
  facialHair: [
    "beardMustache",
    "pyramid",
    "walrus",
    "goatee",
    "shadow",
    "soulPatch",
  ],
  hairColor: ["black", "brunette", "red", "pink", "copper", "blonde", "grey"],
  clothingColor: [
    "blue",
    "turquoise",
    "purple",
    "green",
    "red",
    "yellow",
    "pink",
  ],
  skinColor: [
    "tone1",
    "tone2",
    "tone3",
    "tone4",
    "tone5",
    "tone6",
    "tone7",
    "tone8",
  ],
};

export { avatarDesign };
